# .github/workflows/gradle-build-pr.yml
name: Run Gradle on Push and PRs
# Triggers the workflow on push or pull request events
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        with build-root-directory: /app
        arguments: build